export type RssSource = {
  name: string;
  url: string;
};

export type TelegramSource = {
  name: string;
  channel: string;
  indicator?: boolean;
};

export const RSS_SOURCES: RssSource[] = [
  { name: "Reuters", url: "https://feeds.reuters.com/reuters/worldNews" },
  { name: "ה-WSJ", url: "https://feeds.a.dj.com/rss/RSSWorldNews.xml" },
  { name: "ה-Washington Post", url: "https://feeds.washingtonpost.com/rss/world" },
  { name: "ה-NYT", url: "https://rss.nytimes.com/services/xml/rss/nyt/MiddleEast.xml" },
  { name: "ה-Telegraph", url: "https://www.telegraph.co.uk/rss.xml" },
  { name: "ה-Bloomberg", url: "https://feeds.bloomberg.com/politics/news.rss" },
  { name: "CNN", url: "http://rss.cnn.com/rss/edition_world.rss" },
  { name: "ABC", url: "https://abcnews.go.com/abcnews/internationalheadlines" },
  { name: "Politico", url: "https://rss.politico.com/politics-news.xml" },
  { name: "אלשרק אלאוסט", url: "https://aawsat.com/feed" },
  { name: "אלערבי אלג'דיד", url: "https://www.alaraby.co.uk/rss.xml" },
  { name: "ארם", url: "https://www.eremnews.com/feed" },
  { name: "אלדיאר", url: "https://addiyar.com/rss.xml" },
  { name: "אלג'זירה", url: "https://www.aljazeera.com/xml/rss/all.xml" },
  { name: "פארס", url: "https://www.farsnews.ir/rss" },
  { name: "תסנים", url: "https://www.tasnimnews.com/en/rss/feed/0/8/0" },
  { name: "אירנא", url: "https://www.irna.ir/rss" },
];

export const TELEGRAM_SOURCES: TelegramSource[] = [
  { name: "נאיה", channel: "naya_foriraq" },
  { name: "סברין", channel: "SabrenNewss" },
  { name: "אלמהואר", channel: "Alomhoar" },
  { name: "עלי בכר", channel: "Alibk3" },
  { name: "תסנים", channel: "Tasnimnews" },
  { name: "פארס", channel: "farsna" },
  { name: "מהר", channel: "mehrnews" },
  { name: "רשות השידור האיראנית", channel: "iribnews" },
  { name: "SNN", channel: "snntv" },
  { name: "אירנא", channel: "irna_1313" },
  { name: "נור ניוז", channel: "Nournews_ir" },
  { name: "אלג'דיד", channel: "ALJADEED_NEWS" },
  { name: "MTV", channel: "MTVLebanoNews" },
  { name: "אלמיאדין", channel: "almayadeen" },
  { name: "אלערביה", channel: "alarabiyaBr" },
  { name: "אלחדת'", channel: "alhadath_brk" },
  { name: "אלג'זירה", channel: "AjaNews" },
  { name: "אלג'זירה ישיר", channel: "ajMubasher" },
  { name: "חמזה", channel: "hamza20300" },
  { name: "קדס", channel: "QudsN" },
];

export const X_HANDLES = [
  "FarsNews_Agency",
  "tasnimnews",
  "IRNA_English",
  "PressTV",
  "NourNews_ir",
  "ISNA_news",
  "defapress_ir",
  "AlMayadeenNews",
  "Alakhbar",
  "almanarnews",
  "Reuters",
  "AP",
  "AFP",
  "wsj",
  "axios",
  "ft",
  "nytimes",
  "AJArabic",
  "AlArabiya_Brk",
  "AlHadath_Brk",
  "aawsat_news",
  "anadolu",
  "spagov",
  "wamnews",
  "iranintl",
  "TheCradleMedia",
  "amwajmedia",
  "StateDept",
  "AlMasirahTV",
  "Ansarollah",
  "spagov",
  "kuna_en",
  "wamnews",
  "AlMamlakaTV",
  "AsharqNews",
  "rtarabic",
  "SputnikInt",
  "CENTCOM",
  "SecRubio",
  "IRGC_English",
  "Sepahcybery",
  "MMY1444",
  "Alhashed_media",
  "alahednews",
  "aljadeednews",
  "mtvlebanon",
  "NBNLebanon",
  "Hezbollah",
  "SyrianPresidency",
  "SyrianMOI",
  "IraqiMFA",
  "Yemen_Mofa",
  "JamaranNews",
  "ILNA_English",
  "mehrnews_Ir",
  "Tasnim_English",
  "farsna_en",
  "alkhaleejonline",
  "Alforqan",
  "SawtAlGhad",
  "baghdadtoday",
  "shafaq",
  "RudawEnglish",
  "QudsNen",
  "ShehabAgency",
  "HamasInfoEn",
  "EnabBaladiEn",
  "SkyNewsArabia_B",
  "alaraby_ar",
  "alqudsalarabi",
];

/** Owner X (Twitter) source lists — monitor for exclusives; always open the primary outlet. */
export const X_LISTS: { name: string; id: string; url: string }[] = [
  { name: "list-1", id: "2028039297878634889", url: "https://x.com/i/lists/2028039297878634889" },
  { name: "list-2", id: "193997610", url: "https://x.com/i/lists/193997610" },
  { name: "list-3", id: "193992434", url: "https://x.com/i/lists/193992434" },
  { name: "list-4", id: "1359519988156157954", url: "https://x.com/i/lists/1359519988156157954" },
  { name: "list-5", id: "194023773", url: "https://x.com/i/lists/194023773" },
  { name: "list-6", id: "2029309781169905773", url: "https://x.com/i/lists/2029309781169905773" },
  { name: "list-7", id: "194326098", url: "https://x.com/i/lists/194326098" },
  { name: "list-8", id: "1619207287297511424", url: "https://x.com/i/lists/1619207287297511424" },
];

/** Prefer these hosts when an exclusive is attributed through a secondary paper. */
export const PRIMARY_HOST_HINTS: Record<string, string[]> = {
  iran: ["farsnews.ir", "tasnimnews.com", "irna.ir", "mehrnews.com", "isna.ir", "presstv.ir", "defapress.ir", "snn.ir", "nournews.ir", "iribnews.ir"],
  lebanon: ["almanar.com.lb", "al-akhbar.com", "alahednews.com.lb", "almayadeen.net"],
  yemen: ["almasirah.net", "sabanew.net"],
  iraq: ["shafaq.com", "ina.iq"],
  syria: ["sana.sy"],
};

