export type RssSource = {
  name: string;
  url: string;
};

export type TelegramSource = {
  name: string;
  channel: string;
  indicator?: boolean;
};

export const RSS_SOURCES: RssSource[] = [
  { name: "אלג'זירה", url: "https://www.aljazeera.com/xml/rss/all.xml" },
  {
    name: "אלג'זירה",
    url: "https://www.aljazeera.net/aljazeerarss/a7c186be-1baa-4bd4-9d80-a84db769f779/73d0e1b4-532f-45ef-b680-839ca1d9cb0b",
  },
  { name: "BBC", url: "https://feeds.bbci.co.uk/news/world/middle_east/rss.xml" },
  { name: "BBC ערבית", url: "https://feeds.bbci.co.uk/arabic/rss.xml" },
  { name: "ה-NYT", url: "https://rss.nytimes.com/services/xml/rss/nyt/MiddleEast.xml" },
  { name: "ה-Guardian", url: "https://www.theguardian.com/world/middleeast/rss" },
  { name: "אלמוניטור", url: "https://www.al-monitor.com/rss.xml" },
  { name: "The Cradle", url: "https://thecradle.co/feed" },
  { name: "MEE", url: "https://www.middleeasteye.net/rss.xml" },
  { name: "איראן אינטרנשיונל", url: "https://www.iranintl.com/feed" },
  { name: "פראנס 24", url: "https://www.france24.com/en/middle-east/rss" },
  { name: "פראנס 24 ערבית", url: "https://www.france24.com/ar/middle-east/rss" },
  { name: "אנאדולו", url: "https://www.aa.com.tr/en/rss/default?cat=middle-east" },
  { name: "סאנא", url: "https://sana.sy/en/?feed=rss2" },
  { name: "ה-Axios", url: "https://api.axios.com/feed/" },
  { name: "ה-FT", url: "https://www.ft.com/world/mideast?format=rss" },
  { name: "אקונומיסט", url: "https://www.economist.com/middle-east-and-africa/rss.xml" },
  { name: "סקיי ניוז", url: "https://feeds.skynews.com/feeds/rss/world.xml" },
  { name: "פוקס", url: "https://moxie.foxnews.com/google-publisher/world.xml" },
  { name: "אלשרק אלאוסט", url: "https://aawsat.com/feed" },
  { name: "אלשרק אלאוסט", url: "https://aawsat.com/feed/arab-world" },
  { name: "אלערבי אלג'דיד", url: "https://www.alaraby.co.uk/rss.xml" },
  { name: "אלאח'באר", url: "https://www.al-akhbar.com/rss" },
  { name: "Amwaj", url: "https://amwaj.media/feed" },
  { name: "רודאו", url: "https://www.rudaw.net/english/rss" },
  { name: "כורדיסטן 24", url: "https://www.kurdistan24.net/en/rss" },
  { name: "אנב בלדי", url: "https://www.enabbaladi.net/feed" },
  { name: "אלמסדר", url: "https://almasdaronline.com/rss" },
  { name: "שפק", url: "https://shafaq.com/ar/rss" },
  { name: "Daily Sabah", url: "https://www.dailysabah.com/rss" },
  { name: "טהראן טיימס", url: "https://www.tehrantimes.com/rss" },
  { name: "פארס", url: "https://www.farsnews.ir/rss" },
  { name: "תסנים", url: "https://www.tasnimnews.com/en/rss/feed/0/8/0" },
  { name: "אירנא", url: "https://www.irna.ir/rss" },
  { name: "מהר", url: "https://www.mehrnews.com/rss" },
  { name: "יסנא", url: "https://www.isna.ir/rss" },
  { name: "פרס TV", url: "https://www.presstv.ir/rss" },
  { name: "נור ניוז", url: "https://nournews.ir/en/rss" },
  { name: "אלמיאדין", url: "https://www.almayadeen.net/rss" },
  { name: "אלמנאר", url: "https://www.almanar.com.lb/rss" },
  { name: "The National", url: "https://www.thenationalnews.com/arc/outboundfeeds/rss/?outputType=xml" },
  { name: "אלע'ד", url: "https://alghad.com/rss" },
  { name: "יום7", url: "https://www.youm7.com/rss/rssfeeds" },
  { name: "אהראם", url: "https://english.ahram.org.eg/rss.aspx" },
  { name: "וואפא", url: "https://english.wafa.ps/rss.aspx" },
  { name: "Reuters", url: "https://feeds.reuters.com/reuters/worldNews" },
  { name: "SPA", url: "https://www.spa.gov.sa/rss.xml" },
  { name: "KUNA", url: "https://www.kuna.net.kw/rssenglish.xml" },
  { name: "WAM", url: "https://www.wam.ae/en/rss/latest-news.xml" },
  { name: "אלמסירה", url: "https://www.almasirah.net.ye/rss" },
  { name: "תסנים ערבית", url: "https://www.tasnimnews.com/ar/rss/feed/0/8/0" },
  { name: "מהר ערבית", url: "https://ar.mehrnews.com/rss" },
  { name: "אלאח'באר", url: "https://al-akhbar.com/rss.xml" },
];

export const TELEGRAM_SOURCES: TelegramSource[] = [
  { name: "פארס", channel: "farsna" },
  { name: "תסנים", channel: "tasnimnews" },
  { name: "אירנא", channel: "IRNAofficial" },
  { name: "מהר", channel: "mehrnews" },
  { name: "פרס TV", channel: "PressTV" },
  { name: "נור ניוז", channel: "NourNews_IR" },
  { name: "יסנא", channel: "ISNAnews" },
  { name: "דפא פרס", channel: "defapress" },
  { name: "משרע", channel: "mashreghnews" },
  { name: "חבר אונליין", channel: "khabaronline" },
  { name: "IRIB", channel: "IRIBNEWS" },
  { name: "אלמיאדין", channel: "almayadeen" },
  { name: "אלאח'באר", channel: "AlakhbarNews" },
  { name: "אלמנאר", channel: "almanarnews" },
  { name: "אנאדולו", channel: "anadoluagency" },
  { name: "סאנא", channel: "SyrianArabNews" },
  { name: "אלמסירה", channel: "almasirah" },
  { name: "אנצאר אללה", channel: "Ansarollah_Media" },
  { name: "עדן אלע'ד", channel: "adenalghad_news" },
  { name: "אלמסדר", channel: "almasdaronline" },
  { name: "סבא", channel: "sabanewnet" },
  { name: "שפק", channel: "shafaqnews" },
  { name: "רודאו", channel: "RudawEnglish" },
  { name: "INA", channel: "IraqiNewsAgency" },
  { name: "SPA", channel: "SPAagency" },
  { name: "WAM", channel: "wamnews" },
  { name: "QNA", channel: "QatarNewsQNA" },
  { name: "אלערביה", channel: "AlArabiya" },
  { name: "אלחדת'", channel: "AlHadath" },
  { name: "אלג'זירה", channel: "AJANews" },
  { name: "אלשרק אלאוסט", channel: "aawsat" },
  { name: "אלקודס אלערבי", channel: "alqudsalarabi" },
  { name: "אלערבי אלג'דיד", channel: "alaraby_ar" },
  { name: "סקיי ניוז ערבית", channel: "skynewsarabia" },
  { name: "The Cradle", channel: "TheCradleMedia" },
  { name: "Amwaj", channel: "amwajmedia" },
  { name: "איראן אינטרנשיונל", channel: "IranIntl" },
  { name: "רויטרס", channel: "Reuters" },
  { name: "AFP", channel: "AFPnews" },
  { name: "אנב בלדי", channel: "EnabBaladiNews" },
  { name: "סוריה TV", channel: "SyriaTV" },
  { name: "קדס", channel: "QudsN" },
  { name: "שהאב", channel: "ShehabAgency" },
  { name: "פלע'א", channel: "palinfo" },
  { name: "חמאס", channel: "HamasInfoAr" },
  { name: "נהארנט", channel: "Naharnet" },
  { name: "LBCI", channel: "LBCILebanon" },
  { name: "צאבין", channel: "SabreenNews" },
  { name: "אלמחואר", channel: "almahwar" },
  { name: "האעלאם אלחרבי", channel: "C_Military14" },
  { name: "אלע'ד", channel: "alghadnews" },
  { name: "וואפא", channel: "WAFANewsPS" },
  { name: "Daily Sabah", channel: "dailysabah" },
  { name: "RT ערבית", channel: "rtarabic" },
  { name: "ספוטניק ערבית", channel: "Sputnik_Ar" },
  { name: "אלג'זירה ישיר", channel: "ajmubasher" },
  { name: "אלחדת' דחוף", channel: "Alhadathajel" },
  { name: "אלערביה דחוף", channel: "AlArabiya_Brk" },
  { name: "אלעאלם", channel: "alalam" },
  { name: "יחיא סריע", channel: "MMY1444" },
  { name: "האעלאם אלחרבי תימן", channel: "militarymedia1" },
  { name: "בגדאד היום", channel: "baghdadtodaynews" },
  { name: "חשד שעיבי", channel: "alhashed" },
  { name: "אלעחד", channel: "alahednews" },
  { name: "NBN", channel: "NBNLive" },
  { name: "MTV לבנון", channel: "mtvlebanon" },
  { name: "אלג'דיד", channel: "aljadeednews" },
  { name: "ג'מראן", channel: "JamaranNews" },
  { name: "אילנא", channel: "ilna_ir" },
  { name: "SNN", channel: "snn_ir" },
  { name: "חבר פורי", channel: "khabar_fori" },
  { name: "טהראן פורי", channel: "TehranFori" },
  { name: "הממלכה", channel: "AlMamlakaTV" },
  { name: "אלשרק ניוז", channel: "AsharqNews" },
  { name: "נשיאות סוריה", channel: "SyrianPresidency" },
  { name: "משהפ סוריה", channel: "SyrianMOI" },
  { name: "חדשות חזבאללה", channel: "Hezbollah_News" },
  { name: "אלח'ליג' אונליין", channel: "alkhaleejonline" },
  { name: "משהח עיראק", channel: "IraqiMFA" },
  { name: "משהח תימן", channel: "YemeniMofa" },
  { name: "סאות אלע'ד", channel: "SawtAlGhad" },
  { name: "רשת אלפרקאן", channel: "AlforqanMedia" },
  { name: "צאפא", channel: "SafaPs" },
  { name: "סנד", channel: "SANDnews" },
  { name: "אלאח'באריה אלסוריה", channel: "SyriaNewsAgency" },
  { name: "רויא ניוז", channel: "RoyaNews" },
  { name: "וואע", channel: "INAnew" },
  { name: "אבו עלי אקספרס", channel: "AbuAliExpress", indicator: true },
  { name: "דסק ערבים", channel: "kan11arabic", indicator: true },
];

export const X_HANDLES = [
  "FarsNews_Agency",
  "tasnimnews",
  "IRNA_English",
  "PressTV",
  "NourNews_ir",
  "ISNA_news",
  "defapress_ir",
  "AlMayadeenNews",
  "Alakhbar",
  "almanarnews",
  "Reuters",
  "AP",
  "AFP",
  "wsj",
  "axios",
  "ft",
  "nytimes",
  "AJArabic",
  "AlArabiya_Brk",
  "AlHadath_Brk",
  "aawsat_news",
  "anadolu",
  "spagov",
  "wamnews",
  "iranintl",
  "TheCradleMedia",
  "amwajmedia",
  "StateDept",
  "AlMasirahTV",
  "Ansarollah",
  "spagov",
  "kuna_en",
  "wamnews",
  "AlMamlakaTV",
  "AsharqNews",
  "rtarabic",
  "SputnikInt",
  "CENTCOM",
  "SecRubio",
  "IRGC_English",
  "Sepahcybery",
  "MMY1444",
  "Alhashed_media",
  "alahednews",
  "aljadeednews",
  "mtvlebanon",
  "NBNLebanon",
  "Hezbollah",
  "SyrianPresidency",
  "SyrianMOI",
  "IraqiMFA",
  "Yemen_Mofa",
  "JamaranNews",
  "ILNA_English",
  "mehrnews_Ir",
  "Tasnim_English",
  "farsna_en",
  "alkhaleejonline",
  "Alforqan",
  "SawtAlGhad",
  "baghdadtoday",
  "shafaq",
  "RudawEnglish",
  "QudsNen",
  "ShehabAgency",
  "HamasInfoEn",
  "EnabBaladiEn",
  "SkyNewsArabia_B",
  "alaraby_ar",
  "alqudsalarabi",
];
